### ISSUE TITLE
Nested possible reverts

### ISSUE THREAD

**Issue by colin-morpho** [morpho-org/morpho-token-upgradeable#101]
The style used in the `require` found here
https://github.com/morpho-org/morpho-token-upgradeable/blob/41e7f07bf44925453b7214090f30cef40a62c743/src/DelegationToken.sol#L119 should be avoided as we are nesting out two possible revert causes, one for arithmetic overflows and one for the actual revert condition.

**Comment by colin-morpho** [comment]
Here it's ok because nonce overflows are impossible in practice, but this require style should be avoided.

**Comment by MathisGD** [comment]
What would it change if we were doing the nonce increment outside of the require?

**Comment by colin-morpho** [comment]
Clarify the source of the revert, overflow vs. equality check.

**Comment by MathisGD** [comment]
right now, if the increment overflows, solidity will throw and "arithmetic over/underflow error", while if the equality is false, it will throw the "InvalidDelegationNonce"

exactly like if the increment was done outside

**Comment by colin-morpho** [comment]
Yes, that is true. My point is that upon reading the code having two nested reverts in a single expressions should be avoided, not because the reported issue will no be right, but to improve readability (and possibly debugging).
