### ISSUE TITLE
totalVotingPower getter

### ISSUE THREAD

**Issue by Jean-Grimal** [morpho-org/morpho-token-upgradeable#9]
Right now there is no way to get the total Voting Power
Could be interesting to add a getter

**Comment by Tvenus** [comment]
Hi
I am very interested in your work, and I wanna work with you.

I can develop a smart contract function that calculates total voting power based on user stakes or token holdings.
I can create a dashboard that displays individual and total voting power, voting history, and other relevant metrics.
I can also use visualizations (charts, graphs) to make the data easy to interpret.

Could you please give me an opportunity to work with you?

**Comment by Jean-Grimal** [comment]
Just realized that the `ERC20Votes`'s `_getTotalSupply()` function doesn't return the total amount delegated, but only the total supply of the token,

So it's useless
